name: Lint

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - main

jobs:
  csvlint:
    name: CSV Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run CSV Linter
        uses: jbzoo/csv-blueprint@1.0.3
        with:
          csv: TranslatedMods.csv
          schema: .github/resources/csv-lint-rule.yml
          report: github

  hjsonlint:
    name: HJSON Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Linter
        uses: ExternalLocalizer/TmlHjsonLinter@master

  directory-check:
    name: Directory Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check Directory Structure
        run: |
          line_number=1
          error_found=0

          while read -r internal_name; do
              line_number=$((line_number + 1))
              if [ ! -d "$internal_name" ]; then
                  echo "::error file=TranslatedMods.csv,line=$line_number::Directory $internal_name does not exist"
                  error_found=1
              fi
          done < <(tail -n +2 TranslatedMods.csv | cut -d',' -f3)

          if [ $error_found -eq 1 ]; then
            exit 1
          fi
