name: Lint

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  csvlint:
    name: CSV Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run CSV Linter
        uses: jbzoo/csv-blueprint@1.0.3
        with:
          csv: TranslatedMods.csv
          schema: .github/resources/csv-lint-rule.yml
          report: github

  hjsonlint:
    name: HJSON Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Linter
        uses: ExternalLocalizer/TmlHjsonLinter@master

  directory-check:
    name: Directory Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13' 

      - name: Check Directory Structure
        run: python .github/resources/check_directory_script.py

